version: '3'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ser322_tomcat_stack
    ports:
      - "8080:8080"
    volumes:
      - ./target/:/user/local/tomcat/webapps #change

  postgres:
    image: postgres:latest
    container_name: ser322_postgres_stack
    ports:
      - "32769:5432" #point intellij to port 32769 to access postgres db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin

  adminer:
    image: adminer
    container_name: ser322_adminer_stack
    ports:
      - "8081:8080"
    links:
      - postgres
    restart: "always"
