version: '3'
services:
  tomcat:
    image: tomcat:9.0.31-jdk13-openjdk-oracle
    container_name: ser322_stack_tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./build/libs/:/usr/local/tomcat/webapps
    links:
      - postgres

  postgres:
    image: postgres:latest
    container_name: ser322_stack_postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  adminer:
    image: adminer
    container_name: ser322_stack_adminer
    ports:
      - "8081:8080"
    links:
      - postgres
    restart: "always"
