version: '3'
services:
  tomcat:
    image: tomcat:9.0.31-jdk13-openjdk-oracle
    container_name: ser322_stack_tomcat
    ports:
      - "8080:8080"
    volumes:
      - ../project/target/:/usr/local/tomcat/webapps
    links:
      - postgres
    networks: 
      SER322_net:
          ipv4_address: 172.29.1.2

  postgres:
    image: postgres:latest
    container_name: ser322_stack_postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks: 
      SER322_net:
          ipv4_address: 172.29.1.3

  adminer:
    image: adminer
    container_name: ser322_stack_adminer
    ports:
      - "8081:8080"
    links:
      - postgres
    restart: "always"
    networks: 
      SER322_net:
          ipv4_address: 172.29.1.4
  
  ub:
    image: ubuntu:latest
    container_name: ubuntu_test
    networks: 
      SER322_net:
          ipv4_address: 172.29.1.5
    

networks:
  SER322_net:
    #driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16